const FormActionTypes = {
  START_SEND_FORM: 'START_SEND_FORM',
  SEND_FORM_SUCCESS: 'SEND_FORM_SUCCESS',
  SEND_FORM_FAILURE: 'SEND_FORM_FAILURE',
  RESET_FORM_AFTER_SUCCESS: 'RESET_FORM_AFTER_SUCCESS',
};

export default FormActionTypes;
