const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  START_GOOGLE_SIGN_IN: 'START_GOOGLE_SIGN_IN',
  START_EMAIL_SIGN_IN: 'START_EMAIL_SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION'
};

export default UserActionTypes;
