const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  START_GOOGLE_SIGN_IN: 'START_GOOGLE_SIGN_IN',
  START_EMAIL_SIGN_IN: 'START_EMAIL_SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  START_SIGN_OUT: 'START_SIGN_OUT',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  START_SIGN_UP: 'START_SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
};

export default UserActionTypes;
